<?php

require_once 'DBConn.php';

abstract class DBTask
{
    /**
     * @var array $body The data structure to be iterated
     */
    protected array $body = [];
    public function getInput(): array { return $this->body; }

    /**
     * @param DBConn $conn Database connection
     * @return array Flattened 1D array of OpContext
     */
    abstract function dryRun(DBConn $conn): array;   

    /**
     * Perform batch task with given database connection
     * @param DBConn $conn Database connection
     * @param bool $useTransaction Should the task run inside a transaction ?
     * @throws PDOException If DBConn already has an active transaction and $useTransaction is TRUE
     * @return DBTaskResult A list of OpResult, and extra info
     */
    public function run(DBConn $conn, bool $useTransaction): DBTaskResult
    {
        $isError = FALSE;
        $opContextList = [];
        $opResultList = [];
        
        if ($useTransaction) {
            $opContext = OpContext::beginTransaction();
            $opContext->setTags($conn->getDBInfo());
            $opContextList[] = $opContext;
        }

        $dryRunResult = $this->dryRun($conn);
        $opContextList = array_merge($opContextList, $dryRunResult);
        
        foreach ($opContextList as $opContext) {
            if ($isError || !($opContext instanceof OpContext)) { 
                continue; 
            }
            $opContext->setTags($conn->getDBInfo());
            $opResult = $conn->execContext($opContext);
            $opResultList[] = $opResult;
            $this->onTaskGetOpResult($opResult);
            if (!$opResult->getIsSuccess()) {
                $isError = TRUE;
            }
        }

        if ($useTransaction) {
            if (!$isError) {
                $opContext = OpContext::commit();
            } else {
                $opContext = OpContext::rollBack();
            }
            $opContext->setTags($conn->getDBInfo());
            $opContextList[] = $opContext;
            $opResult = $conn->execContext($opContext);
            $opResultList[] = $opResult;
            $this->onTaskGetOpResult($opResult);
        }
        return new DBTaskResult($opResultList);
    }

    /**
     * No-op in this class.
     * 
     * This function is called inside ADBTask::run, 
     * and is called immediately after calling DBConn::execContext(OpContext),
     * which returns a OpResult instance.
     * 
     * Do something that requires immediate handle of OpResult (E.g. write result into to error log)
     * @param OpResult $opResult 
     * @return void
     */
    protected function onTaskGetOpResult(OpResult $opResult): void { }
}

/**
 * Generated by DBTask::run
 */
class DBTaskResult
{
    private ?OpResult $lastError = NULL;
    public function getLastError(): ?OpResult { return $this->lastError; }

    public function getIsSuccess(): bool { return $this->lastError === NULL; }

    private array $opResultList = [];
    public function getOpResultList(): array { return $this->opResultList; }

    public function __construct(array $arrOpResult)
    {
        foreach ($arrOpResult as $opResult) {
            if ($opResult instanceof OpResult) {
                $this->opResultList[] = $opResult;
            }
        }
        foreach ($this->opResultList as $opResult) {
            if (!$opResult->getIsSuccess()) {
                $this->lastError = $opResult;
            }
        }
    }
}
