<?php

namespace DBTask;

use DBConn\OpResult;

/**
 * Generated by DBTask::run
 */
final class DBTaskResult
{
    private ?OpResult $lastError = NULL;
    public function getLastError(): ?OpResult { return $this->lastError; }

    public function getIsSuccess(): bool { return $this->lastError === NULL; }

    private array $opResultList = [];
    public function getOpResultList(): array { return $this->opResultList; }

    public function __construct(array $opResultList)
    {
        $this->opResultList = array_filter($opResultList, function ($v) { return $v instanceof OpResult; });
        foreach ($this->opResultList as $opResult) {
            if (!$opResult->getIsSuccess()) {
                $this->lastError = $opResult;
            }
        }
    }
}
